apiVersion: api-gateway.gen-ai-cf.intra.hitachi.co.jp/v1
kind: AppRoute
metadata:
  name: openwebui
  namespace: hitachi-pj-workflow-usermanaged
spec:
  requiredAnyRoles:
    - developers
  applicationType: frontend
  target:
    service:
      name: open-webui
      port: 8080