affinity: {}
autoscaling:
  apiVersion: autoscaling/v2beta1
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
config:
  base_url: http://localhost/
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: pj-registry.soft-seigi.intra.hitachi.co.jp/cs3_dify_workflow/apache/tika
  tag: 2.9.0.0
# imagePullSecrets: []
imagePullSecrets:
 - name: regcred
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
livenessProbe:
  failureThreshold: 20
  initialDelaySeconds: 15
  periodSeconds: 5
  scheme: HTTP
  timeoutSeconds: 30
nameOverride: ""
networkPolicy:
  allowExternal: false
  enabled: false
nodeSelector: {}
podAnnotations: {}
podSecurityContext: 
  fsGroup: 1001000000
readinessProbe:
  failureThreshold: 20
  initialDelaySeconds: 15
  periodSeconds: 5
  scheme: HTTP
  timeoutSeconds: 30
replicaCount: 1
resources:
  limits:
    cpu: "2"
    memory: 2000Mi
  requests:
    cpu: "1"
    memory: 1500Mi
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 1001000000
  runAsNonRoot: true
  runAsUser: 1001000000
service:
  port: 9998
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
tolerations: []
